const { Anthropic } = require("@anthropic-ai/sdk");
const { Octokit } = require("@octokit/rest");

const COMMENT_MARKER = "<!-- pr-summary-bot -->";
const MAX_DIFF_CHARS = 40000;

async function run() {
  const token = process.env.GITHUB_TOKEN;
  const apiKey = process.env.ANTHROPIC_API_KEY;
  const eventPath = process.env.GITHUB_EVENT_PATH;
  const repo = process.env.GITHUB_REPOSITORY;

  if (!token || !apiKey || !eventPath || !repo) {
    console.error(
      "Missing required env vars: GITHUB_TOKEN, ANTHROPIC_API_KEY, GITHUB_EVENT_PATH, GITHUB_REPOSITORY"
    );
    process.exit(1);
  }

  const [owner, repoName] = repo.split("/");
  const event = require(eventPath);
  const prNumber = event.pull_request?.number || event.number;

  if (!prNumber) {
    console.log("No PR number found in event payload. Skipping.");
    return;
  }

  const octokit = new Octokit({ auth: token });
  const anthropic = new Anthropic({ apiKey });

  // Fetch PR details
  const { data: pr } = await octokit.pulls.get({
    owner,
    repo: repoName,
    pull_number: prNumber,
  });

  // Fetch the diff
  const { data: diff } = await octokit.pulls.get({
    owner,
    repo: repoName,
    pull_number: prNumber,
    mediaType: { format: "diff" },
  });

  // Fetch changed files list
  const { data: files } = await octokit.pulls.listFiles({
    owner,
    repo: repoName,
    pull_number: prNumber,
  });

  const filesSummary = files
    .map((f) => {
      const icon =
        f.status === "added"
          ? "+"
          : f.status === "removed"
          ? "-"
          : f.status === "renamed"
          ? "~"
          : "M";
      return `${icon} ${f.filename} (+${f.additions} -${f.deletions})`;
    })
    .join("\n");

  // Truncate diff if too large
  const diffStr =
    typeof diff === "string" ? diff : JSON.stringify(diff, null, 2);
  const truncatedDiff =
    diffStr.length > MAX_DIFF_CHARS
      ? diffStr.slice(0, MAX_DIFF_CHARS) +
        `\n\n... [diff truncated at ${MAX_DIFF_CHARS} chars, ${files.length} files total]`
      : diffStr;

  const prompt = `You are a senior code reviewer. Analyze this pull request and write a clear, concise summary.

PR Title: ${pr.title}
PR Description: ${pr.body || "(no description provided)"}
Author: ${pr.user.login}
Base branch: ${pr.base.ref}
Head branch: ${pr.head.ref}

Changed files (${files.length} total):
${filesSummary}

Diff:
\`\`\`diff
${truncatedDiff}
\`\`\`

Write a PR summary with these sections (use markdown):
1. **What this PR does** — 2-3 sentences, plain English, non-technical if possible
2. **Key changes** — bullet list of the 3-6 most important changes (be specific, not generic)
3. **Files changed** — brief note on which areas of the codebase are touched
4. **Potential concerns** — any issues to watch for (edge cases, missing tests, security, breaking changes). If none, say "None identified."
5. **Suggested reviewers** — based on the files changed, what kind of expertise should review this (e.g. "frontend engineer familiar with auth flow", "database admin"). Skip if you can't determine this.

Keep the entire summary under 400 words. Be direct and specific — avoid vague phrases like "various improvements".`;

  console.log(`Generating summary for PR #${prNumber}: ${pr.title}`);

  const message = await anthropic.messages.create({
    model: "claude-haiku-4-5-20251001",
    max_tokens: 1024,
    messages: [{ role: "user", content: prompt }],
  });

  const summary = message.content[0].text;

  const commentBody = `${COMMENT_MARKER}
## PR Summary

${summary}

---
*Generated by [pr-summary](https://github.com/Android-Tipster/pr-summary) using Claude Haiku.*`;

  // Check if a summary comment already exists and update it
  const { data: comments } = await octokit.issues.listComments({
    owner,
    repo: repoName,
    issue_number: prNumber,
  });

  const existingComment = comments.find((c) =>
    c.body.includes(COMMENT_MARKER)
  );

  if (existingComment) {
    await octokit.issues.updateComment({
      owner,
      repo: repoName,
      comment_id: existingComment.id,
      body: commentBody,
    });
    console.log(`Updated existing summary comment #${existingComment.id}`);
  } else {
    const { data: newComment } = await octokit.issues.createComment({
      owner,
      repo: repoName,
      issue_number: prNumber,
      body: commentBody,
    });
    console.log(`Created new summary comment #${newComment.id}`);
  }

  console.log("Done.");
}

run().catch((err) => {
  console.error("Action failed:", err.message);
  process.exit(1);
});
